CREATE TABLE prompts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    prompt TEXT,
    negative_prompt TEXT,
    image_title VARCHAR(255),
    image_description TEXT,
    image_tags TEXT,
    image_categories TEXT,
    job_completed BOOLEAN DEFAULT FALSE,
    job_startdate DATETIME,
    job_completedate DATETIME,
    render_time INT,
    style_selections JSON,
    performance_selection VARCHAR(50),
    aspect_ratios_selection VARCHAR(50),
    image_number INT,
    image_seed BIGINT,
    sharpness TINYINT,
    guidance_scale FLOAT,
    base_model_name VARCHAR(255),
    refiner_model_name VARCHAR(255),
    refiner_switch FLOAT,
    loras JSON,
    advanced_params JSON,
    save_meta BOOLEAN DEFAULT FALSE,
    meta_scheme VARCHAR(50),
    save_extension VARCHAR(10),
    save_name VARCHAR(255),
    read_wildcards_in_order BOOLEAN DEFAULT FALSE,
    require_base64 BOOLEAN DEFAULT FALSE,
    async_process BOOLEAN DEFAULT FALSE,
    webhook_url VARCHAR(255)
);
